# Generated by Django 5.0.2 on 2024-02-21 16:18

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('citizen_number', models.CharField(max_length=255, unique=True, validators=[core.validators.only_int])),
                ('speciality', models.CharField(choices=[('endodontist', 'Endodontist'), ('orthodontist', 'Orthodontist'), ('periodontist', 'Periodontist'), ('prosthodontist', 'Prosthodontist'), ('maxillofacial_surgeon', 'Maxillofacial Surgeon'), ('maxillofacial_radiologist', 'Maxillofacial Radiologist'), ('anesthesiologists', 'Anesthesiologists'), ('maxillofacial_pathologist', 'Maxillofacial Pathologist'), ('pediatric_dentist', 'Pediatric Dentist'), ('orofacial_pain', 'Orofacial Pain'), ('oral_medicine', 'Oral Medicine'), ('dental_public_health', 'Dental Public Health'), ('general_dentistry', 'General Dentistry'), ('cosmetic_dentistry', 'Cosmetic Dentistry'), ('restorative_dentistry', 'Restorative Dentistry'), ('geriatric_dentistry', 'Geriatric dentistry'), ('dental_hygienist', 'Dental Hygienist'), ('dental_assistant', 'Dental Assistant')], default='general_dentistry', max_length=30)),
                ('profile_picture', models.ImageField(upload_to='dentists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
