# Generated by Django 5.0.2 on 2024-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='dentists'),
        ),
    ]
