# Generated by Django 5.0.2 on 2024-02-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0003_dentist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='profile_picture',
        ),
    ]
