# Generated by Django 5.0.2 on 2024-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0002_alter_dentist_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
